### ISSUE TITLE
Add tracking on social sharing button(s)

### ISSUE THREAD

**Issue by groovecoder** [mozilla/mozhacks#20]
- [x] Ask dev-webdev@lists.mozilla.org for examples of privacy-respecting sharing buttons
- [x] Blatantly copy ... er, ... re-use
- [x] Add GA `_trackEvent` for clicks
